backend:
  #name: git-gateway
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: "content/pages/home.md"
        fields:
          - { name: "templatekey", label: "Template Key",  widget: "hidden", default: "home-page" }
          - { name: path, label: Path, widget: hidden }
          - { name: title, label: Title }
          - { name: subtitle, label: Subtitle }
      - name: about
        label: About
        file: "content/pages/about.md"
        fields:
          - { name: "templatekey", label: "Template Key",  widget: "hidden", default: "about-page" }
          - { name: path, label: Path, widget: hidden }
          - { name: title, label: Title }
          - { name: subtitle, label: Subtitle }
